#
# This Python script reads the PNG files in provided folder, extracts pixel data
# and creates one C header file which contains a uint16_t array for each image.
#
# The name of each particular array is constructed as follows:
# <file name without extension>_IMG
# The first half word (2 bytes) of the array provides width of the image, the
# second one - height. After these there is only raw pixel data, 16 bits per
# pixel (R[15:11], G[10:5], B[4:0]).
#

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from PIL import Image
import os

def image_to_hwords(image):
    width, height = image.size
    result = [0] * (width * height)

    for y in range(height):
        for x in range(width):
            r, g, b = image.getpixel((x, y))
            # TODO: there is room for improvement: dithering.
            result[y * width + x] = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    
    return [width, height] + result

def hex_hword(n):
    return f"0x{n:04X}"

def generate_c_array(image_file_path):
    image = Image.open(image_file_path)
    bytes = image_to_hwords(image)
    array_name = os.path.splitext(os.path.basename(image_file_path))[0] + "_IMG"
    result = f"static const uint16_t {array_name}[{len(bytes)}] = {{"

    for i in range(len(bytes)):
        if i % 10 == 0:
            result += "\n"
        result += hex_hword(bytes[i])
        result += ", "
    
    result += "};"

    return result

def main():
    arg_parser = ArgumentParser(description="""
    This Python script reads the PNG files in provided folder, extracts pixel
    data and creates one C header file which contains a uint16_t array for each image.
    """, formatter_class=RawDescriptionHelpFormatter
    )
    arg_parser.add_argument("--input", "-i", metavar="<path to folder with images>", type=str, required=True)
    arg_parser.add_argument("--output", "-o", metavar="<.h file path>", type=str, required=True)
    args = arg_parser.parse_args()

    result = f"""// AUTOGENERATED FILE. DO NOT EDIT!
#ifndef IMAGES_H
#define IMAGES_H

#include <stdint.h>

"""

    for file in os.listdir(args.input):
        full_path = os.path.join(args.input, file)
        if not os.path.isfile(full_path):
            continue

        result += generate_c_array(full_path) + "\n\n"

    result += "#endif // IMAGES_H"
    
    file_out = open(args.output, "w")
    file_out.write(result)

if __name__ == "__main__":
    main()
